version: '3.8'

services:
  discord-bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./twitch_usernames.json:/app/twitch_usernames.json  # Mount the JSON file as a volume
    command: python src/main.py
    restart: always